//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


const calculateFibbonaci = limit =>{
   let x = 0
   let y = 1
   let sum = 0
   let result = x + y
   x = result
   
   while(result <= limit){
      result = x + y
      if(result % 2 === 0) sum += result
      y = x
      x = result
   }
   return `The sum is: ${sum}`
}

console.log(calculateFibbonaci(4000000))

